COLUMNS:
  show_id: object
  type: object
  title: object
  director: object
  cast: object
  country: object
  date_added: object
  release_year: int64
  rating: object
  duration: object
  listed_in: object
  description: object 