artifacts_root : artifacts 

data_ingestion:
  root_dir : artifacts/data_ingestion  
  local_data_file : artifacts/data_ingestion/netflix_dataset.csv

data_validation:
  root_dir : artifacts/data_validation
  status_file : artifacts/data_validation/status.txt
  local_data_file : artifacts/data_ingestion/netflix_dataset.csv

